### ISSUE TITLE
UserWarning: telegram.Emoji is being deprecated

### ISSUE THREAD

**Issue by BadBoySeventeen** [jh0ker/mau_mau_bot#32]
`[root@kant mau_mau_bot]# python3 bot.py 
/usr/local/lib/python3.5/site-packages/telegram/emoji.py:37: UserWarning: telegram.Emoji is being deprecated, please see https://git.io/v6DeB
  warnings.warn("telegram.Emoji is being deprecated, please see https://git.io/v6DeB")
/usr/local/lib/python3.5/site-packages/telegram/emoji.py:37: UserWarning: telegram.Emoji is being deprecated, please see https://git.io/v6DeB
  warnings.warn("telegram.Emoji is being deprecated, please see https://git.io/v6DeB")
/usr/local/lib/python3.5/site-packages/telegram/ext/messagehandler.py:88: UserWarning: Using a list of filters in MessageHandler is getting deprecated, please use bitwise operators (& and |) instead. More info: https://git.io/vPTbc.
  warnings.warn('Using a list of filters in MessageHandler is getting '
&
`
i think maybe need update? but how to update or need u update?
@jh0ker

**Comment by BadBoySeventeen** [comment]
sorry for that code...i first comment issues

**Comment by cogumm** [comment]
up

**Comment by Karho** [comment]
I have decided to remove the dependence on telegram.emoji and directly use the emoji instead. 

Thanks for your notice.

**Comment by BadBoySeventeen** [comment]
So how to run bot
Is this warning that I can not use it?

2017年5月4日 下午2:17，"Karho" <notifications@github.com>写道：

**Comment by Karho** [comment]
@BadBoySeventeen

It is no harm to use the code now and the warning appears is because the code is now based on the deprecated features in the Python package python-telegram-bot.   

> So how to run bot
> Is this warning that I can not use it?
