### ISSUE TITLE
Error in bluff calling

### ISSUE THREAD

**Issue by axusmark** [jh0ker/mau_mau_bot#67]
I found a error when I'd have only two cards: a DRAW_FOUR and a RED SKIP card.
The current card in game was a YELLOW 4. I threw the DRAW_FOUR, and then I chose the color red. After that, the next player called a bluff. I received 4 cards.

**Comment by DO97** [comment]
You've probably surpassed the 108 cards, right? In my opinion, this is a bug that happens in that special case. It happened to me only in that circumstances.
@jh0ker

**Comment by jh0ker** [comment]
Thanks to @DO97 for helping solve this
