### ISSUE TITLE
Error: Type Error

### ISSUE THREAD

**Issue by ACH1980** [jh0ker/mau_mau_bot#69]
I've the following problem:
![image](https://user-images.githubusercontent.com/39656381/62909045-405d6380-bd7b-11e9-9141-a3b731e3ef17.png)

**Comment by ACH1980** [comment]
I've followed all steps in README.md

**Comment by 7DSMeliodas** [comment]
it seems the .po havent converted to .mo

**Comment by ACH1980** [comment]
Yes. That was the problem. Btw: The Paths aren't hardcoded, but it's not tested, that the script runs in the correct directory...
