### ISSUE TITLE
Unable to see stickers inside inline query

### ISSUE THREAD

**Issue by blurdylan** [jh0ker/mau_mau_bot#88]
Since Telegram update 2.1.10, I cannot see the cards stickers in the inline query box. It is just empty spaces but clickable. It still works but I do not know what cards I am playing.

**Comment by blurdylan** [comment]
Behaves as this https://github.com/telegramdesktop/tdesktop/issues/3317

**Comment by DO97** [comment]
Well, this seems to be a Telegram related issue

**Comment by jh0ker** [comment]
you can click and hold on each sticker to make the cards show up, see https://github.com/telegramdesktop/tdesktop/issues/8020 for the new bug report

**Comment by blurdylan** [comment]
It was fixed in Telegram 2.1.12
I can close this
