### ISSUE TITLE
randomly add player?

### ISSUE THREAD

**Issue by idealhack** [jh0ker/mau_mau_bot#9]
How about change the way of appending players to random in case of cheating?

For example, change `players.append(player)` to `players.insert(randrange(len(players) + 1), player)`.

I would like to send a patch.

**Comment by jh0ker** [comment]
@idealhack Do you mean to prevent players from working together? Please read issue #6 and check the related PR - you might want to wait with the patch until the PR is merged.

**Comment by idealhack** [comment]
OK, let's do this later.

**Comment by idealhack** [comment]
I’m closing this because of inactive. Feel free to open again if it’s necessary.
