### ISSUE TITLE
Can't bluff

### ISSUE THREAD

**Issue by fabifont** [jh0ker/mau_mau_bot#99]
I saw that it is possible to call a bluff but there is no way to bluff so that option is useless.

**Comment by jh0ker** [comment]
Please read the **Wild Draw 4 Card** section in the [official rules](https://service.mattel.com/instruction_sheets/42001pr.pdf). 

The **Call Bluff** option refers to the challenging mechanic explained in the second half of that section. "Bluffing" in this context refers to playing a **Wild Draw 4 Card** illegally, which is indeed possible.

Feel free to re-open if you believe this does not resolve your issue.
